import mojnp from '/icons/mojnp.svg';
import apple from '/icons/apple.svg';
import brainwave from '/icons/brainwave.svg';
import edofrizer from '/icons/edo-frizer.svg';
import logosmall from '/icons/logo-small.svg';
import vercellogo from '/icons/vercel-logo.svg';
import mojnpSS from '/images/mojnpss.png';
import appleSS from '/images/appless.png';
import brainwaveSS from '/images/brainwavess.png';
import aoraSS from '/images/aorass.jpeg';
import sociallySS from '/images/sociallyss.png';
import edofrizerSS from '/images/edofrizerss.png';

export const mojnpLogo = mojnp;
export const appleLogo = apple;
export const brainwaveLogo = brainwave;
export const edofrizerLogo = edofrizer;
export const aoraLogo = logosmall;
export const vercelLogo = vercellogo;
export const mojnpss = mojnpSS;
export const appless = appleSS;
export const brainwavess = brainwaveSS;
export const aorass = aoraSS;
export const sociallyss = sociallySS;
export const edofrizerss = edofrizerSS;
