import mojnp from '/icons/mojnp.svg';
import apple from '/icons/apple.svg';
import brainwave from '/icons/brainwave.svg';
import edofrizer from '/icons/edo-frizer.svg';
import logosmall from '/icons/logo-small.svg';
import vercellogo from '/icons/vercel-logo.svg';
import mojnpSS from '/images/mojnpss.png';
import appleSS from '/images/appless.png';
import brainwaveSS from '/images/brainwavess.png';
import aoraSS from '/images/aorass.jpeg';
import sociallySS from '/images/sociallyss.png';
import edofrizerSS from '/images/edofrizerss.png';
import appwrite from '/icons/app.svg';
import clerk from '/icons/c.svg';
import gsap from '/icons/gsap.svg';
import css from '/icons/css.svg';
import html from '/icons/html.svg';
import js from '/icons/js.svg';
import prisma from '/icons/prisma.svg';
import react from '/icons/re.svg';
import tailwind from '/icons/tail.svg';
import three from '/icons/three.svg';
import typescript from '/icons/ts.svg';
import nextjs from '/icons/nextjs.svg';
import reactnative from '/icons/rn.svg';
import expo from '/icons/expo.svg';

export const mojnpLogo = mojnp;
export const appleLogo = apple;
export const brainwaveLogo = brainwave;
export const edofrizerLogo = edofrizer;
export const aoraLogo = logosmall;
export const vercelLogo = vercellogo;
export const mojnpss = mojnpSS;
export const appless = appleSS;
export const brainwavess = brainwaveSS;
export const aorass = aoraSS;
export const sociallyss = sociallySS;
export const edofrizerss = edofrizerSS;
export const appwriteLogo = appwrite;
export const clerkLogo = clerk;
export const gsapLogo = gsap;
export const cssLogo = css;
export const htmlLogo = html;
export const jsLogo = js;
export const prismaLogo = prisma;
export const reactLogo = react;
export const tailwindLogo = tailwind;
export const threeLogo = three;
export const typescriptLogo = typescript;
export const nextjsLogo = nextjs;
export const reactnativeLogo = reactnative;
export const expoLogo = expo;
